// AUTOGENERATED, DO NOT MODIFY

// [[[[INFO>
// Copyright 2015 Epicycle (http://epicycle.org, https://github.com/open-epicycle)
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// For more information check https://github.com/open-epicycle/Epicycle.Geodesy-cs
// ]]]]

using Epicycle.Graphics;
using System.Xml.Linq;

namespace Epicycle.Geodesy.Kml
{
    internal sealed class SegmentKmlElement : IKmlElement
    {
        public SegmentKmlElement(GeoPoint3 start, GeoPoint3 end, Color4b? colour = null)
        {
            _start = start;
            _end = end;
            _colour = colour;
        }

        private readonly GeoPoint3 _start;
        private readonly GeoPoint3 _end;
        private readonly Color4b? _colour;

        public XElement ToXml()
        {
            var coordText = string.Format("{0},{1},{2} {3},{4},{5}",
                _start.Longtitude_deg, _start.Latitude_deg, _start.Altitude,
                _end.Longtitude_deg, _end.Latitude_deg, _end.Altitude);

            var xml = 
                new XElement("Placemark", 
                    new XElement("LineString",
                        new XElement("coordinates", coordText)
                    )
                );

            if (_colour != null)
            {
                var colourText = string.Format("{0:X2}{1:X2}{2:X2}{3:X2}", _colour.Value.A, _colour.Value.B, _colour.Value.G, _colour.Value.R);

                xml.Add(
                    new XElement("Style",
                        new XElement("LineStyle",
                            new XElement("color", colourText)
                            )
                        )
                    );
            }

            return xml;
        }
    }
}
