// AUTOGENERATED, DO NOT MODIFY

// [[[[INFO>
// Copyright 2015 Epicycle (http://epicycle.org, https://github.com/open-epicycle)
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// For more information check https://github.com/open-epicycle/Epicycle.Geodesy-cs
// ]]]]

using Epicycle.Commons;

namespace Epicycle.Geodesy
{
    using System;

    public sealed class SexagesimalAngle
    {
        public SexagesimalAngle(double degrees)
        {
            double arcminutesFraction;

            ToSexagesimalFraction(degrees, out _degrees, out arcminutesFraction);

            ToSexagesimalFraction(arcminutesFraction, out _arcminutes, out _arcseconds);
        }

        public SexagesimalAngle(int degrees, double arcminutes)
        {
            _degrees = degrees;

            ToSexagesimalFraction(arcminutes, out _arcminutes, out _arcseconds);
        }

        private static void ToSexagesimalFraction(double real, out int integralPart, out double fractionalPart)
        {
            integralPart = (int)Math.Floor(real);

            fractionalPart = 60 * (real - integralPart);
        }

        public SexagesimalAngle(int degrees, int arcminutes, double arcseconds)
        {
            _degrees = degrees;
            _arcminutes = arcminutes;
            _arcseconds = arcseconds;
        }

        private readonly int _degrees;
        private readonly int _arcminutes;
        private readonly double _arcseconds;

        public int Degrees
        {
            get { return _degrees; }
        }

        public int Arcminutes
        {
            get { return _arcminutes; }
        }

        public double Arcseconds
        {
            get { return _arcseconds; }
        }

        public double ArcminutesFraction
        {
            get { return Arcminutes + Arcseconds / 60; }
        }

        public double InDegrees
        {
            get { return Degrees + ArcminutesFraction / 60; }
        }

        public double InRadians
        {
            get { return BasicMath.DegToRad(InDegrees); }
        }

        public override string ToString()
        {
            return string.Format("{0}° {1}' {2}''", Degrees, Arcminutes, Arcseconds);
        }

        public static SexagesimalAngle FromRadians(double rad)
        {
            return new SexagesimalAngle(BasicMath.RadToDeg(rad));
        }
    }
}
