title: Epicycle.Geodesy (.NET)
url: https://github.com/open-epicycle/Epicycle.Geodesy-cs
summary: "Epicycle .NET geodesy library. Includes: 2D and 3D LLA geo-point, WGS84/ECEF/ENU conversions, simple KML serialization."

organization: Epicycle
tags: epicycle lib library geodesy geography gps geopoint lla ecef enu datum wgs84 kml
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Geodesy-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.6.0
 - Epicycle.Math-cs.0.1.3.0
 - Epicycle.Graphics-cs.0.1.3.0

description: |
   Epicycle .NET geodesy library. Includes: 2D and 3D LLA geo-point, WGS84/ECEF/ENU conversions, simple KML serialization.
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.Geodesy-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.Geodesy-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.Geodesy-cs